<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-UA48023" ignored="0" name="Default test" tests="5" failures="1" timestamp="27 Jul 2022 20:23:22 GMT" time="16.63" errors="0">
  <testcase name="janResult" time="0.381" classname="shoeStore.com.shoe.HomePageTest"/>
  <testcase name="febResult" time="0.411" classname="shoeStore.com.shoe.HomePageTest"/>
  <testcase name="marchresult" time="0.878" classname="shoeStore.com.shoe.HomePageTest"/>
  <testcase name="Aprresult" time="0.651" classname="shoeStore.com.shoe.HomePageTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [April&amp;apos;s Shoes] but found [March&amp;apos;s Shoes]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [April's Shoes] but found [March's Shoes]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at shoeStore.com.shoe.HomePageTest.Aprresult(HomePageTest.java:69)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Aprresult -->
  <testcase name="DecResult" time="0.693" classname="shoeStore.com.shoe.HomePageTest"/>
</testsuite> <!-- Default test -->
